config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopapp.urls', namespace='shopapp')),
    path('materials/', include('blogapp.urls', namespace='blogapp')),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from blogapp.views import UserMaterialListView
from shopapp.views import UserProducts
from users.apps import UsersConfig
from users.views import UserRegistration, LoginView, LogoutView, UserDetailView, UserUpdateView, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('register/', UserRegistration.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserDetailView.as_view(), name='profile'),
    path('edit/', UserUpdateView.as_view(), name='edit'),
    path('respassword/', reset_password, name='respassword'),
    path('products/', UserProducts.as_view(), name='user_products'),
    path('materials/', UserMaterialListView.as_view(), name='user_materials')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Country(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='Почта')
    first_name = models.CharField(max_length=150, verbose_name='Имя')
    last_name = models.CharField(max_length=150, verbose_name='Фамилия')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    phone = models.IntegerField(verbose_name='Номер телефона', **NULLABLE)
    country = models.OneToOneField(Country, on_delete=models.SET_NULL, verbose_name='Страна', **NULLABLE)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2',)


class UserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('avatar', 'first_name', 'last_name', 'email', 'phone', 'country', 'password',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random

from django.conf import settings
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, UpdateView

from users.forms import UserRegisterForm, UserForm
from users.models import User


class UserRegistration(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('users:login')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data()
        context_data['intent'] = 'register'
        return context_data

    def form_valid(self, form):
        new_user = form.save()
        if form.is_valid():
            send_mail(
                subject='Добро пожаловать на сайт!',
                message='Приветствую Вас! Вы зарегистрировались на сайте E&I Company. '
                        'Здесь вы можете найти любую технику для работы на вкус',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[new_user.email],
            )
        return super().form_valid(form)


class LoginView(BaseLoginView):
    template_name = 'users/login.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['intent'] = 'login'
        return context_data


class LogoutView(BaseLogoutView):
    pass


class UserDetailView(DetailView):
    model = User

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data()
        context_data['intent'] = 'profile'
        return context_data


class UserUpdateView(UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data()
        context_data['intent'] = 'edit'
        return context_data


def reset_password(request):
    new_password = ''.join([str(random.randint(1, 9)) for _ in range(15)])
    send_mail(
        subject='Смена пароля!',
        message=f'Ваш временный пароль: {new_password}. Поторопитесь изменить его!',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email],
    )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('shopapp:main'))

users/templates/users/includes/inc_users_auth.html
{% load crispy_forms_tags %}
{% load users_tags %}

<div class="col-12">
    <div class="row">
        <div class="col-6 mx-auto my-auto">
            <div class="card">
                <div class="card-header">
                    <h3 class="my-0 font-weight-normal" align="center">{{ intent|login_or_register_header }}</h3>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary btn-block mt-4">{{ intent|login_or_register }}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

users/templates/users/includes/inc_users_navbar.html
{% load my_tags %}

<div class="col-3">
    <div class="card">
        <div class="card-body">
            <div class="avatar mb-2">
                <img src="{{ user.avatar|mymedia }}" alt="Avatar"><br>
            </div>
            <h5 class="card-text"><b>{{ user.first_name }}</b></h5>
            <h5 class="card-text"><b>{{ user.last_name }}</b></h5>
            <a href="{% url 'users:edit' %}" class="card-text">Редактировать</a>
            <a href="{% url 'users:user_products' %}" class="btn btn-light mt-4">Мои товары</a>
            <a href="{% url 'users:user_materials' %}" class="btn btn-light mt-2">Мои статьи</a>
        </div>
    </div>
</div>