config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopapp.urls', namespace='shopapp')),
    path('materials/', include('blogapp.urls', namespace='blogapp')),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from shopapp.apps import ShopappConfig
from shopapp.views import (CategoryListView, ProductDetailView, ProductListView, ProductCategoryListView,
                           ProductCreateView, ProductUpdateView, toggle_material)

app_name = ShopappConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='main'),
    path('categories/', cache_page(60)(CategoryListView.as_view()), name='all_categories'),
    path('goods/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='one_good'),
    path('category/<int:pk>/', ProductCategoryListView.as_view(), name='one_category'),
    path('add/', ProductCreateView.as_view(), name='add_product'),
    path('edit/<int:pk>/', ProductUpdateView.as_view(), name='product_edit'),
    path('activity/<int:pk>/', toggle_material, name='toggle_material')
]

users/urls.py
from django.urls import path

from blogapp.views import UserMaterialListView
from shopapp.views import UserProducts
from users.apps import UsersConfig
from users.views import UserRegistration, LoginView, LogoutView, UserDetailView, UserUpdateView, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('register/', UserRegistration.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserDetailView.as_view(), name='profile'),
    path('edit/', UserUpdateView.as_view(), name='edit'),
    path('respassword/', reset_password, name='respassword'),
    path('products/', UserProducts.as_view(), name='user_products'),
    path('materials/', UserMaterialListView.as_view(), name='user_materials')
]

shopapp/models.py
from django.db import models
from django.core import validators

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='Наименование')
    content = models.TextField(verbose_name='Описание', **NULLABLE)
    image = models.ImageField(upload_to='shopapp/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey('Category', null=True, on_delete=models.CASCADE, verbose_name='Категория')
    amount = models.IntegerField(
        verbose_name='Цена за покупку',
        validators=[validators.MinValueValidator(1, message='Товар не может стоить меньше 1 рубля')]
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего изменения')
    is_published = models.BooleanField(default=True, verbose_name='Опубликован')

    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='Продукт', **NULLABLE)

    def __str__(self):
        return f'{self.name}: {self.amount}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('-created_at',)


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Наименование', unique=True)
    image = models.ImageField(upload_to='shopapp/', verbose_name='Изображение', **NULLABLE)
    content = models.TextField(verbose_name='Описание', **NULLABLE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    number = models.IntegerField(verbose_name='Номер версии')
    name = models.CharField(max_length=100, verbose_name='Название версии')
    is_current_version = models.BooleanField(default=True, verbose_name='Является текущей версией?')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

shopapp/forms.py
from django import forms

from config.settings import FORBIDDEN_WORDS
from .models import Product, Version


def check_words(clean_data, forbidden_words, verbose_name):
    if clean_data.lower() in forbidden_words:
        raise forms.ValidationError(f"В поле '{verbose_name}' обнаружено запрещённое слово")


class ProductForm(forms.ModelForm):
    def clean_name(self):
        clean_data = self.cleaned_data.get('name')
        verbose_name = self.fields.get('name').label
        check_words(clean_data, FORBIDDEN_WORDS, verbose_name)
        return clean_data

    def clean_content(self):
        clean_data = self.cleaned_data.get('content')
        verbose_name = self.fields.get('content').label
        check_words(clean_data, FORBIDDEN_WORDS, verbose_name)
        return clean_data

    class Meta:
        model = Product
        fields = ('name', 'content', 'category', 'image', 'amount',)


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

shopapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from shopapp.models import Category, Product, Version
from .forms import ProductForm, VersionForm
from .services import get_cache_for_product_detail, get_cache_for_category


class BaseProductListView(LoginRequiredMixin, ListView):
    model = Product

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        name = self.request.GET.get("query")
        if name:
            queryset = queryset.filter(name__icontains=name)
        return queryset

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        hidden_objects = Product.objects.filter(is_published=False)

        context_data['user'] = self.request.user
        context_data['hidden_objects'] = hidden_objects

        for product in context_data.get('object_list'):
            product.version = product.version_set.filter(is_current_version=True).first()

        return context_data


class ProductListView(BaseProductListView):
    pass


class ProductCategoryListView(BaseProductListView):
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(category_id=self.kwargs.get('pk'))
        return queryset


class UserProducts(BaseProductListView):
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user_id=self.request.user)
        return queryset


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        object_list = get_cache_for_category(self.get_queryset())
        context_data['object_list'] = object_list

        return context_data


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        product = get_cache_for_product_detail(self.object, self.object.pk)
        context_data['object'] = product

        return context_data


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('users:user_products')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = 'shopapp.change_product'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user and not self.request.user.is_staff:
            raise Http404
        return self.object

    def get_success_url(self):
        return reverse('shopapp:product_edit', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data()
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)
        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


@login_required
def toggle_material(request, pk):
    material = get_object_or_404(Product, pk=pk)
    if material.is_published:
        material.is_published = False
    else:
        material.is_published = True

    material.save()
    return redirect(reverse('shopapp:main'))

shopapp/templates/shopapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Pricing example for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/pricing.css' %}" rel="stylesheet">
    <link href="{% static 'css/newstyles.css' %}" rel="stylesheet">
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">
</head>

<body>
{% include 'shopapp/includes/inc_shopapp_menu.html' %}
<div class="container">
    {% block content %}
    {% endblock %}
    {% include 'shopapp/includes/inc_shopapp_under.html' %}
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/bootstrap.slim.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
<script>
    Holder.addTheme('thumb', {
      bg: '#55595c',
      fg: '#eceeef',
      text: 'Thumbnail'
    });
</script>
</body>
</html>

shopapp/templates/shopapp/categories.html
{% extends 'shopapp/base.html' %}


{% block content %}
<div class="row">
    {% for object in object_list %}
    <div class="col-4">
        <div class="card-deck mb-3 text-center">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.name|title }}</h1>
                    {% if object.image %}
                    <img class="displayed_img" src="/media/{{ object.image }}">
                    {% else %}
                    <img class="displayed_img" src="/media/shopapp/not_found.jpeg">
                    {% endif %}
                    <p class="card-text">{{ object.content }}</p>
                    <a href="{% url 'shopapp:one_category' pk=object.pk %}"><button type="button" class="btn btn-lg btn-block btn-primary">Посмотреть</button></a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

shopapp/templates/shopapp/category_list.html
{% extends 'shopapp/base.html' %}

{% load my_tags %}

{% block content %}
<div class="row">
    {% for object in object_list %}
    <div class="col-4">
        <div class="card-deck mb-3 text-center">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.name|title }}</h1>
                    <img class="displayed_img" src="{{ object.image|mymedia }}">
                    <p class="card-text">{{ object.content }}</p>
                    <a href="{% url 'shopapp:one_category' pk=object.pk %}"><button type="button" class="btn btn-lg btn-block btn-primary">Посмотреть</button></a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

shopapp/templates/shopapp/good.html
{% extends 'shopapp/base.html' %}
{% load my_tags %}
{% block content %}
<div class="header">
    <h1>{{ object.name }}</h1>
</div>
<div class="good">
    <div class="row">
        {% if object.image %}
        <div class="col-6">
            <img class="good_logo" src="{{ object.image| mymedia }}">
        </div>
        {% else %}
        <div class="col-6">
            <img class="good_logo" src="/media/shopapp/404.jpeg">
        </div>
        {% endif %}
        <div class="col-6">
            <h4><b>Характеристики:</b></h4>
            <div class="description">
                <p>Цена: {{ object.amount }} рублей</p>
                <p>Категория: {{ category_object.name }}</p>
                {% if object.content %}
                <p>Описание: {{ object.content|slice:100 }}</p>
                {% else %}
                <p>Описание: Отсутствует</p>
                {% endif %}
            </div>
            <div class="buy">
                <a href="#" class="btn btn-primary btn-lg">Купить</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

shopapp/templates/shopapp/product_detail.html
{% extends 'shopapp/base.html' %}
{% load my_tags %}
{% block content %}
<div class="col-12 mt-5">
    <div class="row">
        <div class="col-6" align="center">
            <img class="good_logo" src="{{ object.image| mymedia }}">
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h4 align="center"><b>Характеристики</b></h4>
                </div>
                <div class="card-body">
                    <p><b>Название:</b> {{ object.name }} </p>
                    <p><b>Цена:</b> {{ object.amount }} ₽</p>
                    <p><b>Категория:</b> {{ object.category.name }}</p>
                    <p><b>Описание:</b> {{ object.content|check_content }}</p>
                    <p><b>Владелец:</b> {{ object.user|check_owner }}</p>
                </div>
                <div class="card-footer">
                    <a href="#" class="btn btn-primary btn-block">Купить</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% load crispy_forms_tags %}
{% load my_tags %}

{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        {% if object %}
        <div class="row">
            <div class="col-6">
        {% endif %}
                <div class="card">
                    <div class="card-header" align="center">
                        <h3>{{ object|edit_or_create_good }}</h3>
                    </div>
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary btn-lg btn-block mt-3">{{ object|edit_or_create_button }}</button>
                    </div>
                </div>
            </div>
            {% if object %}
            {% include 'shopapp/includes/inc_shopapp_inline_factory.html' %}
            {% endif %}
        </div>
    </form>
</div>
{% endblock %}

shopapp/templates/shopapp/product_list.html
{% extends 'shopapp/base.html' %}
{% load my_tags %}
{% block content %}
<div class="search">
    <form method="get">
        <input class="form-control" type="search" name="query" placeholder="Найдите нужный товар по названию...">
    </form>
</div>
<div class="row">
    {% for object in object_list %}
    <div class="col-4 mb-3">
        <div class="card" style="width: 18rem;">
            <img class="displayed_img" src="{{ object.image|mymedia }}">
            <div class="card-body">
                <h5 class="card-title mt-2">{{ object.name }}</h5>
                <p class="card-text">{{ object.amount }} ₽</p>
                <p class="card-text">{{ object.version.name|check_version }}</p>
                <a href="{% url 'shopapp:one_good' object.pk %}" class="btn btn-primary btn-block">Подробнее</a>
                {% if perms.shopapp.change_product %}
                <a href="{% url 'shopapp:product_edit' object.pk %}" class="btn btn-outline-primary btn-block mt-2">Редактировать</a>
                <a href="{% url 'shopapp:toggle_material' object.pk %}" class="btn btn-outline-warning btn-block mt-2">Деактивировать</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% empty %}
    <h2 class="header mt-4">Товары не найдены</h2>
    {% endfor %}
</div>
{% if user|is_moderator %}
<h2 class="mt-3 mb-3">Скрытые продукты</h2>
<div class="row">
    {% for hidden_object in hidden_objects %}
    <div class="col-4 mb-3">
        <div class="card text-muted" style="width: 18rem;">
            <img class="hidden_img" src="{{ hidden_object.image|mymedia }}">
            <div class="card-body">
                <h5 class="card-title mt-2">{{ hidden_object.name }}</h5>
                <p class="card-text">{{ hidden_object.amount }} ₽</p>
                <p class="card-text">{{ hidden_object.version.name|check_version }}</p>
                <a href="{% url 'shopapp:toggle_material' hidden_object.pk %}"
                   class="btn btn-outline-warning btn-block mt-2">Активировать</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}