blogapp/urls.py
from django.urls import path

from blogapp.apps import BlogappConfig
from blogapp.views import (MaterialListView, MaterialDetailView, MaterialCreateView, MaterialUpdateView,
                           MaterialDeleteView, toggle_material)

app_name = BlogappConfig.name

urlpatterns = [
    path('', MaterialListView.as_view(), name='main'),
    path('view/<int:pk>/', MaterialDetailView.as_view(), name='one_material'),
    path('edit/<int:pk>/', MaterialUpdateView.as_view(), name='edit_material'),
    path('delete/<int:pk>/', MaterialDeleteView.as_view(), name='delete_material'),
    path('add/', MaterialCreateView.as_view(), name='add_material'),
    path('activity/<int:pk>/', toggle_material, name='toggle_material')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopapp.urls', namespace='shopapp')),
    path('materials/', include('blogapp.urls', namespace='blogapp')),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopapp/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from shopapp.apps import ShopappConfig
from shopapp.views import (CategoryListView, ProductDetailView, ProductListView, ProductCategoryListView,
                           ProductCreateView, ProductUpdateView, toggle_material)

app_name = ShopappConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='main'),
    path('categories/', cache_page(60)(CategoryListView.as_view()), name='all_categories'),
    path('goods/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='one_good'),
    path('category/<int:pk>/', ProductCategoryListView.as_view(), name='one_category'),
    path('add/', ProductCreateView.as_view(), name='add_product'),
    path('edit/<int:pk>/', ProductUpdateView.as_view(), name='product_edit'),
    path('activity/<int:pk>/', toggle_material, name='toggle_material')
]

users/urls.py
from django.urls import path

from blogapp.views import UserMaterialListView
from shopapp.views import UserProducts
from users.apps import UsersConfig
from users.views import UserRegistration, LoginView, LogoutView, UserDetailView, UserUpdateView, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('register/', UserRegistration.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserDetailView.as_view(), name='profile'),
    path('edit/', UserUpdateView.as_view(), name='edit'),
    path('respassword/', reset_password, name='respassword'),
    path('products/', UserProducts.as_view(), name='user_products'),
    path('materials/', UserMaterialListView.as_view(), name='user_materials')
]

shopapp/models.py
from django.db import models
from django.core import validators

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='Наименование')
    content = models.TextField(verbose_name='Описание', **NULLABLE)
    image = models.ImageField(upload_to='shopapp/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey('Category', null=True, on_delete=models.CASCADE, verbose_name='Категория')
    amount = models.IntegerField(
        verbose_name='Цена за покупку',
        validators=[validators.MinValueValidator(1, message='Товар не может стоить меньше 1 рубля')]
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, null=True, verbose_name='Дата последнего изменения')
    is_published = models.BooleanField(default=True, verbose_name='Опубликован')

    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='Продукт', **NULLABLE)

    def __str__(self):
        return f'{self.name}: {self.amount}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('-created_at',)


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Наименование', unique=True)
    image = models.ImageField(upload_to='shopapp/', verbose_name='Изображение', **NULLABLE)
    content = models.TextField(verbose_name='Описание', **NULLABLE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    number = models.IntegerField(verbose_name='Номер версии')
    name = models.CharField(max_length=100, verbose_name='Название версии')
    is_current_version = models.BooleanField(default=True, verbose_name='Является текущей версией?')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

shopapp/forms.py
from django import forms

from config.settings import FORBIDDEN_WORDS
from .models import Product, Version


def check_words(clean_data, forbidden_words, verbose_name):
    if clean_data.lower() in forbidden_words:
        raise forms.ValidationError(f"В поле '{verbose_name}' обнаружено запрещённое слово")


class ProductForm(forms.ModelForm):
    def clean_name(self):
        clean_data = self.cleaned_data.get('name')
        verbose_name = self.fields.get('name').label
        check_words(clean_data, FORBIDDEN_WORDS, verbose_name)
        return clean_data

    def clean_content(self):
        clean_data = self.cleaned_data.get('content')
        verbose_name = self.fields.get('content').label
        check_words(clean_data, FORBIDDEN_WORDS, verbose_name)
        return clean_data

    class Meta:
        model = Product
        fields = ('name', 'content', 'category', 'image', 'amount',)


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

shopapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from shopapp.models import Category, Product, Version
from .forms import ProductForm, VersionForm
from .services import get_cache_for_product_detail, get_cache_for_category


class BaseProductListView(LoginRequiredMixin, ListView):
    model = Product

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        name = self.request.GET.get("query")
        if name:
            queryset = queryset.filter(name__icontains=name)
        return queryset

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        hidden_objects = Product.objects.filter(is_published=False)

        context_data['user'] = self.request.user
        context_data['hidden_objects'] = hidden_objects

        for product in context_data.get('object_list'):
            product.version = product.version_set.filter(is_current_version=True).first()

        return context_data


class ProductListView(BaseProductListView):
    pass


class ProductCategoryListView(BaseProductListView):
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(category_id=self.kwargs.get('pk'))
        return queryset


class UserProducts(BaseProductListView):
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user_id=self.request.user)
        return queryset


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        object_list = get_cache_for_category(self.get_queryset())
        context_data['object_list'] = object_list

        return context_data


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        product = get_cache_for_product_detail(self.object, self.object.pk)
        context_data['object'] = product

        return context_data


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('users:user_products')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = 'shopapp.change_product'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user and not self.request.user.is_staff:
            raise Http404
        return self.object

    def get_success_url(self):
        return reverse('shopapp:product_edit', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data()
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)
        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


@login_required
def toggle_material(request, pk):
    material = get_object_or_404(Product, pk=pk)
    if material.is_published:
        material.is_published = False
    else:
        material.is_published = True

    material.save()
    return redirect(reverse('shopapp:main'))

shopapp/templates/shopapp/includes/inc_shopapp_inline_factory.html
{% load crispy_forms_tags %}

<div class="col-6">
    <div class="card">
        <div class="card-header" align="center">
            <h3>Версии</h3>
        </div>
        <div class="card-body">
            {{ formset.management_form }}
            {% for form in formset.forms %}
            {{ form|crispy }}
            {% endfor %}
            <button type="submit" class="btn btn-primary btn-lg btn-block mt-3">Создать</button>
        </div>
    </div>
</div>

shopapp/templates/shopapp/includes/inc_shopapp_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">E&I Shop</h5>
    <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="{% url 'shopapp:main' %}">Главная</a>
        <a class="p-2 text-dark" href="{% url 'shopapp:all_categories' %}">Категории</a>
        <a class="p-2 text-dark" href="{% url 'shopapp:add_product' %}">Добавить товар</a>
        <a class="p-2 text-dark" href="{% url 'blogapp:main' %}">Блог</a>
        <a class="p-2 text-dark" href="{% url 'blogapp:add_material' %}">Добавить блог</a>
    </nav>
    {% if user.is_authenticated %}
    {% if user.is_staff %}
    <a class="btn btn-outline-danger mr-3" href="/admin">Админка</a>
    {% endif %}
    <a class="btn btn-outline-primary mr-3" href="{% url 'users:profile' %}">Профиль</a>
    <form action="{% url 'users:logout' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger mr-3">Выйти</button>
    </form>
    {% else %}
    <a class="btn btn-outline-primary mr-3" href="{% url 'users:login' %}">Войти</a>
    <a class="btn btn-outline-primary" href="{% url 'users:register' %}">Зарегистрироваться</a>
    {% endif %}
</div>

shopapp/templates/shopapp/includes/inc_shopapp_under.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <p class="my-0 mr-md-auto font-weight-normal">E&I Shop</p>
        <small class="d-block mb-3 text-muted">&copy; 2024</small>
      </div>
      <div class="col-6 col-md">
        <h5>Наши партнёры</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Xiaomi</a></li>
          <li><a class="text-muted" href="#">Apple</a></li>
          <li><a class="text-muted" href="#">Honor</a></li>
          <li><a class="text-muted" href="#">Huawei</a></li>
          <li><a class="text-muted" href="#">Сбербанк</a></li>
          <li><a class="text-muted" href="#">СДЭК</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Социальные сети</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Vkontakte</a></li>
          <li><a class="text-muted" href="#">Telegram</a></li>
          <li><a class="text-muted" href="#">WhatsApp</a></li>
          <li><a class="text-muted" href="#">Viber</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>О нас</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Наша цели</a></li>
          <li><a class="text-muted" href="#">Наши магазины</a></li>
        </ul>
      </div>
    </div>
</footer>