blogapp/urls.py
from django.urls import path

from blogapp.apps import BlogappConfig
from blogapp.views import (MaterialListView, MaterialDetailView, MaterialCreateView, MaterialUpdateView,
                           MaterialDeleteView, toggle_material)

app_name = BlogappConfig.name

urlpatterns = [
    path('', MaterialListView.as_view(), name='main'),
    path('view/<int:pk>/', MaterialDetailView.as_view(), name='one_material'),
    path('edit/<int:pk>/', MaterialUpdateView.as_view(), name='edit_material'),
    path('delete/<int:pk>/', MaterialDeleteView.as_view(), name='delete_material'),
    path('add/', MaterialCreateView.as_view(), name='add_material'),
    path('activity/<int:pk>/', toggle_material, name='toggle_material')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopapp.urls', namespace='shopapp')),
    path('materials/', include('blogapp.urls', namespace='blogapp')),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from blogapp.views import UserMaterialListView
from shopapp.views import UserProducts
from users.apps import UsersConfig
from users.views import UserRegistration, LoginView, LogoutView, UserDetailView, UserUpdateView, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('register/', UserRegistration.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserDetailView.as_view(), name='profile'),
    path('edit/', UserUpdateView.as_view(), name='edit'),
    path('respassword/', reset_password, name='respassword'),
    path('products/', UserProducts.as_view(), name='user_products'),
    path('materials/', UserMaterialListView.as_view(), name='user_materials')
]

blogapp/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
    body = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blogapp/', verbose_name='Превью', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    view_count = models.IntegerField(default=0, verbose_name='Количество просмотров')

    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='Пользователь', **NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'запись'
        verbose_name_plural = 'записи'

blogapp/forms.py
from django import forms

from blogapp.models import Blog


class BlogFrom(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'body', 'preview')

blogapp/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from blogapp.forms import BlogFrom
from blogapp.models import Blog
from shopapp.views import LoginRequiredMixin


class MaterialListView(LoginRequiredMixin, ListView):
    model = Blog

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data()

        hidden_objects = Blog.objects.filter(is_published=False)

        context_data['user'] = self.request.user
        context_data['hidden_objects'] = hidden_objects

        return context_data


class UserMaterialListView(MaterialListView):
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user_id=self.request.user)
        return queryset


class MaterialDetailView(LoginRequiredMixin, DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        if self.object.view_count == 100:
            send_mail('Поздравляем со 100 просмотрами!',
                      f'Ваше объявление "{self.object.title}" достигло 100 просмотров!',
                      'skypro.test.testov@yandex.ru',
                      [self.request.user],
                      fail_silently=False
                      )
        self.object.save()
        return self.object


class MaterialCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogFrom
    success_url = reverse_lazy('blogapp:main')

    def form_valid(self, form):
        if form.is_valid():
            new_material = form.save()
            new_material.slug = slugify(new_material.title)
            new_material.save()

        return super().form_valid(form)


class MaterialUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Blog
    permission_required = 'blogapp.change_material'
    fields = ('title', 'body', 'preview')

    def get_success_url(self):
        return reverse('blogapp:one_material', args=[self.kwargs.get('pk')])


class MaterialDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blogapp:main')


def toggle_material(request, pk):
    material = get_object_or_404(Blog, pk=pk)
    if material.is_published:
        material.is_published = False
    else:
        material.is_published = True

    material.save()
    return redirect(reverse('blogapp:main'))

blogapp/templates/blogapp/blog_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                      <p>Хотите удалить материал "{{ object.title }}"?</p>
                      <button type="submit" class="btn btn-danger">Удалить</button>
                      <a href="{% url 'blogapp:main' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blogapp/templates/blogapp/blog_detail.html
{% extends 'shopapp/base.html' %}
{% load my_tags %}
{% block content %}
<div class="header mb-5">
    <h1>{{ object.title }}</h1>
</div>
<div class="row justify-content-center text-center">
    <img class="good_logo" src="{{ object.preview| mymedia }}">
    <div class="col-12 mt-5">
        <p><b>{{ object.body }}</b></p>
        <p>Количество просмотров: {{ object.view_count }}</p>
    </div>
</div>
{% endblock %}

blogapp/templates/blogapp/blog_form.html
{% extends 'shopapp/base.html' %}

{% load crispy_forms_tags %}
{% load blog_tags %}

{% block content %}
<div class="col-12 mx-auto my-auto">
    <div class="card">
        <div class="card-header">
            <h2 align="center">Заполните поля для того, чтобы добавить блог</h2>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-lg btn-block mt-4">{{ object|save_or_edit }}</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blogapp/templates/blogapp/blog_list.html
{% extends 'shopapp/base.html' %}
{% load blog_tags %}
{% block content %}
<div class="col-12">
    <div class="row">
        {% for object in object_list %}
        <div class="col-6">
            <div class="card">
                <img class="displayed_img mt-3" src="{{ object.preview| mymedia }}">
                <div class="card-title mt-4">
                    <a href="{% url 'blogapp:one_material' object.pk %}" class="card-title"><h5 align="center">{{ object.title }}</h5></a>
                </div>
                {% if perms.blogapp.change_blog %}
                <div class="card-footer" align="center">
                    <a href="{% url 'blogapp:edit_material' object.pk %}" class="btn btn-info mt-2 mr-2">Изменить</a>
                    <a href="{% url 'blogapp:toggle_material' object.pk %}" class="btn btn-warning mt-2 mr-2">Деактивировать</a>
                    {% if perms.blogapp.delete_blog %}
                    <a href="{% url 'blogapp:delete_material' object.pk %}" class="btn btn-danger mt-2">Удалить</a>
                    {% endif %}
                </div>
                {% endif %}
            </div>
        </div>
        {% empty %}
        <h2 class="header">Статьи не найдены</h2>
        {% endfor %}
    </div>
    {% if user|is_content_manager %}
    <h2 class="mt-3 mb-3">Скрытые статьи</h2>
    <div class="row">
        {% for hidden_object in hidden_objects %}
        <div class="col-6 mb-3">
            <div class="card text-muted">
                <img class="displayed_img mt-3" src="{{ hidden_object.preview| mymedia }}">
                <div class="card-title mt-4">
                    <a href="{% url 'blogapp:one_material' hidden_object.pk %}" class="card-title"><h5 align="center">{{ hidden_object.title }}</h5></a>
                </div>
                <div class="card-footer" align="center">
                    <a href="{% url 'blogapp:toggle_material' hidden_object.pk %}" class="btn btn-warning mt-2 mr-2">Активировать</a>
                    {% if perms.blogapp.delete_blog %}
                    <a href="{% url 'blogapp:delete_material' hidden_object.pk %}" class="btn btn-danger mt-2">Удалить</a>
                </div>
                {% endif %}
            </div>
        {% endfor %}
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}